name: Adds all issues to project Infix & C:o

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project Infix&co
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/kernelkit/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
