name: Manny the Manager

on:
  workflow_dispatch:
    inputs:
      cleanup:
        required: true
        type: boolean

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Disk inventory ...
        run: |
          echo "df -h ========================================================================="
          df -h
          echo "mounts ========================================================================"
          mount
      - name: File inventory ...
        run: |
          echo "Current directory: $(pwd)"
          echo "Files in $HOME ================================================================"
          ls $HOME
          echo "Find $HOME ===================================================================="
          find $HOME
      - name: Container inventory ...
        run: |
          echo "Available container images: ==================================================="
          docker images
          echo "Available containers: ========================================================="
          docker ps -a
  cleanup:
    if: ${{ inputs.cleanup }}
    needs: inventory
    runs-on: ubuntu-latest
    steps:
      - name: Cleaning up cruft ...
        run: |
          docker image prune -af
          docker volume prune -f
          docker container prune -f
