# This job can be started by a git tag or using the workflow dispatch.
#
# The version string *must* be of the format: vYY.MM(-alphaN|-betaN|-rcN)
#
# In /etc/os-release this string is used for VERSION, VERSION_ID, and
# IMAGE_VERSION, with the 'v' prefix.  In release artifact filenames,
# and zip file directory names, the 'v' is dropped per convention.
name: Release General

on:
  push:
    tags:
      - 'v[0-9]*.*'
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:
  build:
    if: github.repository == 'kernelkit/infix' && startsWith(github.ref, 'refs/tags/')
    name: Build Infix ${{ github.ref_name }} [${{ matrix.platform }}-${{ matrix.variant }}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [aarch64, x86_64]
        variant: [netconf, classic]
      fail-fast: false
    steps:
      - name: Maintenance
        run: |
          docker image prune -af
          docker volume prune -f
          docker container prune -f
      - uses: actions/checkout@v4
      - name: Set Release Variables
        id: vars
        run: |
          if [ -n "${{ inputs.version }}" ]; then
              ver=${{ inputs.version }}
          else
              ver=${GITHUB_REF#refs/tags/}
          fi
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          if echo $ver | grep -qE 'v[0-9\.]+(-alpha|-beta|-rc)[0-9]*'; then
            echo "pre=true"  >> $GITHUB_OUTPUT
          else
            echo "pre=false" >> $GITHUB_OUTPUT
          fi
          fver=${ver#v}
          if [ "${{ matrix.variant }}" = "netconf" ]; then
              target=${{ matrix.platform }}-${fver}
          else
              target=${{ matrix.platform }}-${{ matrix.variant }}-${fver}
          fi
          echo "dir=infix-$target"        >> $GITHUB_OUTPUT
          echo "tgz=infix-$target.tar.gz" >> $GITHUB_OUTPUT
          echo "out=/mnt/x-$target"       >> $GITHUB_OUTPUT
      - name: Restore Cache of dl/
        uses: actions/cache@v4
        with:
          path: dl/
          key: dl-${{ matrix.variant }}-${{ hashFiles('.git/modules/buildroot/HEAD', 'configs/*', 'package/*/*.hash') }}
          restore-keys: |
            dl-${{ matrix.variant }}-
            dl-
      - name: Restore Cache of .ccache/
        uses: actions/cache@v4
        with:
          path: .ccache/
          key: ccache-${{ matrix.platform }}-${{ hashFiles('.git/modules/buildroot/HEAD', 'package/*/*.hash') }}
          restore-keys: |
            ccache-${{ matrix.platform }}-
            ccache-
      - name: Configure & Build
        env:
          INFIX_RELEASE: ${{ steps.vars.outputs.ver }}
        run: |
          if [ "${{ matrix.variant }}" = "netconf" ]; then
              target=${{ matrix.platform }}_defconfig
          else
              target=${{ matrix.platform }}_${{ matrix.variant }}_defconfig
          fi
          echo "Building $target ..."
          sudo mkdir ${{ steps.vars.outputs.out }}
          sudo chown $(id -un):$(id -gn) ${{ steps.vars.outputs.out }}
          export O=${{ steps.vars.outputs.out }}
          make $target
          make
      - name: Prepare Artifact
        run: |
          cd ${{ steps.vars.outputs.out }}
          mv images ${{ steps.vars.outputs.dir }}
          ln -s ${{ steps.vars.outputs.dir }} images
          tar chfz ${{ steps.vars.outputs.tgz }} ${{ steps.vars.outputs.dir }}
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.vars.outputs.out }}/${{ steps.vars.outputs.tgz }}
          name: artifact-${{ matrix.variant }}-${{ matrix.platform }}
  release:
    name: Release Infix ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: "artifact-*"
          merge-multiple: true
      - name: Create checksums ...
        run: |
          for file in *.tar.gz; do
              sha256sum $file > $file.sha256
          done
      - name: Extract ChangeLog entry ...
        run: |
          awk '/^-----*$/{if (x == 1) exit; x=1;next}x' doc/ChangeLog.md \
              |head -n -1 > release.md
          cat release.md
      - uses: ncipollo/release-action@v1
        with:
          name: Infix ${{ github.ref_name }}
          prerelease: ${{ needs.build.outputs.pre }}
          bodyFile:  release.md
          artifacts: "*.tar.gz*"
      - name: Summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          # Infix ${{ github.ref_name }} Released! :rocket:
          
          For the public download links of this release, please see:
           <https://github.com/kernelkit/infix/releases/tag/${{ github.ref_name }}>
          EOF
